### ISSUE TITLE
Prepare Svelte Flow launch blog post on xyflow.com

### ISSUE THREAD

**Issue by johnrobbjr** [xyflow/web#186]
Working Branch: https://github.com/xyflow/web/tree/blog/svelte-launch

To do

- [ ] make fitview work for examples in blog post, currently they start with 0,0 at top-left corner of canvas @peterkogo 
- [ ] Create complex-ish example for "...and beyond" section @peterkogo 
- [ ] Create nice example for intro of post @peterkogo 
- [x] Get hello-world example to appear (currently throws 404, https://xyflow-svelte-examples.vercel.app/blog/svelte-launch/hello-world, does it need to be somehow "uploaded" to vercel or something to work?)
- [x] make copy-text on blog posts look prettier (play with leading, spacing, font size. Use Medium as a reference)

**Comment by chrtze** [comment]
@johnrobbjr this seems to be done? https://www.xyflow.com/blog/svelte-flow-launch
