### ISSUE TITLE
fix web audio tutorial

### ISSUE THREAD

**Issue by chrtze** [xyflow/web#187]
- [ ] when accessing the web audio guide through the sidebar, the sound is being played instantly. we should turn it off by default.
- [x] the first image is broken: https://reactflow-website.vercel.app/learn/tutorials/react-flow-and-the-web-audio-api
- [x] the title of the post should be the original title ("Tutorial: Integrating React Flow and the Web Audio API"), sidebar title should stay the same as it is now

**Comment by hayleigh-dot-dev** [comment]
> when accessing the web audio guide through the sidebar, the sound is being played instantly. we should turn it off by default.

I'm struggling to reproduce this, but I went ahead and explicitly suspended all the audio contexts so they definitely won't make noise until resumed manually.
