### ISSUE TITLE
`onMove`: incorrect event type

### ISSUE THREAD

**Issue by morsko1** [xyflow/web#211]
`event` type is incorrect in `onMove`, `OnMoveStart` and `OnMoveEnd`

According to the type in [react-flow repo](https://github.com/wbkd/react-flow) `event` type should be `MouseEvent | TouchEvent`, not `MouseEvent`
https://github.com/wbkd/react-flow/blob/main/packages/core/src/types/general.ts#L43

**Comment by hayleigh-dot-dev** [comment]
Fixed whenever we next deploy from staging :)
