### ISSUE TITLE
Download Image example resulting image is cropped

### ISSUE THREAD

**Issue by oskar-anderson** [xyflow/web#212]
## Description

I want to implement full diagram PNG export.
The documentation contains an example using [html-to-image](https://github.com/bubkoo/html-to-image) library about downloading the diagram as PNG:
* [documentation](https://reactflow.dev/docs/examples/misc/download-image/)
* [Code sandbox](https://codesandbox.io/s/6gxsmh)

Unfortunately, the image downloaded from the example is cropped on large diagrams. This should not happen judging by the comment:
```
// we calculate a transform for the nodes so that all nodes are visible
```
In addition the image is very pixelated. 

Setting `pixelRatio: 4` seems to fix the pixelation, but I was unable to stop the image cropping.

## Expected behavior
The documentation should contain an example on downloading full diagram as PNG that: 
* Is high quality
* Does not crop the image

https://github.com/wbkd/react-flow-docs/assets/72770213/5960a5a6-268b-4add-8f28-c7e5bdded9a0

**Comment by moklick** [comment]
Hey @oskar-anderson 

you need to adjust the `getTransformForBounds` a bit so that it allows even smaller min zooms (4th param). This should do it:

```js 
const transform = getTransformForBounds(
  nodesBounds,
  imageWidth,
  imageHeight,
  // sets allowed minZoom=0.1 
  0.1,
  2
);
```
