### ISSUE TITLE
fix resize rotate example

### ISSUE THREAD

**Issue by peterkogo** [xyflow/web#214]
https://reactflow.dev/examples/nodes/resize-rotate is broken.
It is deprecated anyways, maybe we should replace it with a working Node Resizer example?

also related to https://github.com/xyflow/xyflow/issues/2777

**Comment by chrtze** [comment]
@peterkogo good catch - this example itself is already built with the node resizer. Maybe we need to adjust the deprecation message to make that more clear?

**Comment by hayleigh-dot-dev** [comment]
Example fixed ✅ Deprecation message made clearer ✅
