### ISSUE TITLE
Pro Platform: top most margin missing on all pages except Dashboard

### ISSUE THREAD

**Issue by peterkogo** [xyflow/web#216]
This is ok

![Image](https://github.com/xyflow/web/assets/7165378/59113aa7-2bee-4c13-a4c9-0c3ab7398039)

Here it is missing
![Image](https://github.com/xyflow/web/assets/7165378/96dff639-e4ad-4ebb-a3c0-d74fa69b5107)

**Comment by peterkogo** [comment]
Only happening when not subscribed an the banner is showing

**Comment by chrtze** [comment]
closing this because we won't fix issues with the current pro platform, focusing on the new platform.
