### ISSUE TITLE
apply for showcase

### ISSUE THREAD

**Issue by lancemao** [xyflow/web#221]
Hey there,

Cool flow made by cool people, love it!

So inspired by xyflow and unreal engine, we made a visual programming language: Hongtu or 鸿图 in Chinese. Hopefully, it can be added to xyflow showcase

https://console.kaihong.com/hongtu/

We took the hard work to make a full blow programming language, features:

* Javascript like data types
* All control flows plus Parrallel & Converge
* Variables and functions
* Event driven
* Node copy&paste
* Undo redo
* Visually backend service development and serverless deployment
* Built-in support for LLM (based on ChatGLM) with Intention-Entity prompt
* More intuitive and extensible Node-resizer that can wrap any custom node (try select mulitple nodes and add commet)
* Animated edge like Postman flow
* Built-in BI charts
* Full life-cycle IOT development
* Export flow to javascript
* Light & dark mode

Thanks in advance!

-Lance Mao

**Comment by johnrobbjr** [comment]
@lancemao we're missing some information that we would need to be able to consider it for the showcase, can you please add the information available our new issue template: https://github.com/xyflow/web/issues/new?assignees=&labels=showcase&projects=&template=submit-showcase.yaml

You can either do this by changing the description of this issue, or submitting a new issue using the linked template

**Comment by lancemao** [comment]
created new using the template. so close this one
