### ISSUE TITLE
svelteflow: installation instructions for pnpm and yarn are displayed incorrectly

### ISSUE THREAD

**Issue by microdou** [xyflow/web#225]
### Code of Conduct

- [x] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Which site are you suggesting a change for?

reactflow.dev

### What content is affected by this change?

https://svelteflow.dev/learn/getting-started/installation

### What part(s) of the article would you like to see updated?

Installation instructions for pnpm & yarn are mixed.

For example, pnpm instruction incorrectly shows
```sh
yarn add @xyflow/svelte
```

### Additional information

Should be an easy fix at [`sites/svelteflow.dev/src/pages/learn/getting-started/installation.mdx`](https://github.com/xyflow/web/blob/e9785ea2fa3be4ff4b53ea157a4b9086282469ee/sites/svelteflow.dev/src/pages/learn/getting-started/installation.mdx#L24C1-L24C24)

**Comment by chrtze** [comment]
Thanks @microdou, fixed in latest version.
