### ISSUE TITLE
fix pagination on theming guide

### ISSUE THREAD

**Issue by chrtze** [xyflow/web#227]
from discord (https://discord.com/channels/771389069270712320/1118204997671334019/1170457263945826344)

Issue : on https://svelteflow.dev/
at bottom of this Page : https://svelteflow.dev/learn/guides/theming
API Refrence doesn't work it should go on : this Page : https://svelteflow.dev/api-reference
Problem : It doesn't redirect just goes at  https://svelteflow.dev/learn/guides/theming

**Comment by chrtze** [comment]
Same issue happens on the reactflow website:

Issue : on https://reactflow.dev/
at bottom of this Page : https://reactflow.dev/learn/troubleshooting/migrate-to-v10
API Refrence doesn't work it should go on : this Page : https://reactflow.dev/api-reference
Problem : It doesn't redirect just goes at  https://reactflow.dev/learn/troubleshooting/migrate-to-v10

**Comment by hayleigh-dot-dev** [comment]
Same issue here too: https://reactflow.dev/learn/customization/custom-nodes

The problem arises when we have external links in the sidebar. I think it's a problem we can't fix.. I'll open an issue with Nextra and see what they say.

**Comment by chrtze** [comment]
> I think it's a problem we can't fix..

That's fine. I'll move it to the backlog again so that we get back to it at some point. Thanks @hayleigh-dot-dev!
