### ISSUE TITLE
PyFlowAutomator, created with SvelteFlow

### ISSUE THREAD

**Issue by Kinthamen** [xyflow/web#228]
PyFlowAutomator is a web-based visual scripting UI for the PyFlowAutomatorCore engine. It's built to handle the needs of both individual users and enterprises, and can be deployed horizontally or vertically to scale with your environment. Its core purpose is to enable users to write python scripts remotely through a user-friendly UI, and with the PyFlowAutomatorCore REST backend its easy to automate runbooks, act as a first responder to alerts or incidents, and more. You can use any functions in any Python package or create custom functions to run on the backend and create the corresponding nodes in the frontend, making it highly extendable.

Frontend (made with SvelteFlow)
https://github.com/Kinthamen/PyFlowAutomator

Backend (Python)
https://github.com/Kinthamen/PyFlowAutomatorCore

**Comment by Kinthamen** [comment]
Image for reference, but also has gifs in readme: <img width="1918" alt="PyFlowAutomator" src="https://github.com/xyflow/web/assets/10972270/5ec0a151-f032-43b9-9a9a-f9fd647b2de3">

**Comment by johnrobbjr** [comment]
PyFlowAutomator has been added to the showcase! Thanks for submitting ✨ https://svelteflow.dev/showcase
