### ISSUE TITLE
Synthesizer tutorial is not muted by default

### ISSUE THREAD

**Issue by moklick** [xyflow/web#238]
When I access the synthesizer tutorial via the sidebar, the sound plays immediately.

**Comment by hayleigh-dot-dev** [comment]
Can you provide a reproduction for this? I can't reproduce this behaviour in chrome or safari.

**Comment by chrtze** [comment]
for me the same issue still happens (Chrome, MacOS):

- open https://reactflow.dev/learn
- click the guide in the sidebar
- sound is playing

sometimes it doesn't happen, then you might reproduce it by clicking something else in the sidebar and then going back to the audio guide.

**Comment by hayleigh-dot-dev** [comment]
I still couldn't reproduce but it should be fixed now. Please re-open if it's _still_ not fixed next time you try..
