### ISSUE TITLE
Attio Showcase Submission

### ISSUE THREAD

**Issue by viralpickaxe** [xyflow/web#245]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Attio (Automations)

### Project Description

Build out flexible workflows to automate common actions across your CRM processes

### Project Tags

automation, no-code, builder, crm, ai

### Link to the project website

attio.com/automations

### Used Library

React Flow

### Upload a Project Screenshot

<img width="1122" alt="product screenshot" src="https://github.com/xyflow/web/assets/3677891/2c728195-64c8-426c-9b2d-f74aecef6494">

### Additional Information

We have a free plan which gives you access to try out Automations so not completely paywalled!

**Comment by johnrobbjr** [comment]
Attio Automations has been added to the showcase! https://reactflow.dev/showcase
