### ISSUE TITLE
google search shows wrong description

### ISSUE THREAD

**Issue by chrtze** [xyflow/web#247]
why is google pulling the description from the license/support section?

![Image](https://github.com/xyflow/web/assets/3797215/586af3e6-6cb8-4c40-b41f-130c5ace68d6)

**Comment by moklick** [comment]
Let's see if [ca55bb3](https://github.com/xyflow/web/commit/ca55bb3c3985a0c9d17270480bafb1c455d9dfb6) fixes it.

**Comment by hayleigh-dot-dev** [comment]
![Screenshot 2023-12-18 at 13 44 04](https://github.com/xyflow/web/assets/9001354/e9fccc4f-eb01-4223-b0df-9a38141a9bdf)
