### ISSUE TITLE
Apply for showcase

### ISSUE THREAD

**Issue by lancemao** [xyflow/web#249]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Hongtu

### Project Description

Hongtu is a general  visual script language.

### Link to the project website

https://hongtu.pub

### Used Library

React Flow

### Upload a Project Screenshot

![Screenshot 2023-11-12 095357](https://github.com/xyflow/web/assets/5020396/b084cf75-dd2d-4e79-b53b-58af07b5754e)

**Comment by lancemao** [comment]
We've been working on English documentation:

https://hongtu.pub/docs/en/

**Comment by johnrobbjr** [comment]
Hey @lancemao, echoing what @moklick said here that it's hard to understand how to use the app when it loads with just two nodes in the flow. 

I will close this issue for now. When you can provide a link to an example that shows a full working flow (like the one in the screenshot), then re-open this issue and it will be considered for the showcase. Thanks for submitting!
