### ISSUE TITLE
Open Source Page: Create Github Star Chart

### ISSUE THREAD

**Issue by moklick** [xyflow/web#26]
* [x] redefine final content and structure @johnrobbjr (basically redo the format)
* [x] implement design 
* [x] make a better version of the thincrust/opencore graphic
* [x] styling for mobile
* [x] update links
* [x] Code embedded github star chart

**Comment by hayleigh-dot-dev** [comment]
For now let's embed a star chart from here: https://github.com/star-history/star-history.

<img width="819" alt="Screenshot 2023-11-03 at 00 31 24" src="https://github.com/xyflow/web/assets/9001354/d6023669-2538-417b-848b-79b45747eed5">

The star history charts are quite popular and the xkcd style is quite charming. We can revisit if we want something more directly in-keeping with our design but closing for now.
