### ISSUE TITLE
Apply for showcase

### ISSUE THREAD

**Issue by bbg** [xyflow/web#265]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

mmapx

### Project Description

Mindmap creation board

### Project Tags

mindmap, notes

### Link to the project website

https://github.com/bbg/mmapx

### Link to project demo

https://mmapx.batuhangoksu.com/

### Used Library

React Flow

### Upload a Project Screenshot

![CleanShot 2023-11-21 at 15 33 18@2x](https://github.com/xyflow/web/assets/13348876/9d91155f-66c4-4d20-9386-f4394af6bbd0)

### Additional Information

I had in mind to make a board of colored note blocks. I wanted to have colorful colored note blocks on my board and be able to link them together when needed. I started my work to learn the Reactflow library and to realize this idea in my mind and after a few days of work, MMapx was born. I want to develop the MMapx project further. I will continue to develop the project by adding more beautiful features over time.

**Comment by johnrobbjr** [comment]
Hey @bbg , I like the project but it's not as far along in development as the other projects we have in the showcase. I'll close this issue for now, but feel free to re-open the issue if you add new features / use cases to the project. Thanks for taking the time to submit!
