### ISSUE TITLE
how can we improve the pro example pages?

### ISSUE THREAD

**Issue by chrtze** [xyflow/web#269]
right now, the pro example pages are missing some important information on what you are getting and how to subscribe. here are some ideas how to enhance it:

- add more information on what problem the example is solving
- add information on what exactly can be customized
- list the parameters that can be passed to the components (maybe with the props table component)
- add some pricing information
- maybe some FAQs on how you can use them
- list dependencies (with version information) and requirements (like which RF or react version you need)
- link to other pro examples

**Comment by hayleigh-dot-dev** [comment]
> list dependencies (with version information) and requirements (like which RF or react version you need)

Could repurpose the props table component for that, would look quite nice I think.

**Comment by johnrobbjr** [comment]
Variant A (Pro Example Features, then preview)
![Image](https://github.com/xyflow/web/assets/9868315/9c901e21-6865-4c09-ad6c-3d0fb5601114)

Variant B (code sandbox with hidden code)
![Image](https://github.com/xyflow/web/assets/9868315/5842e7a2-8913-43ac-9438-04d0a8ab4efb)


Variant C (code sandbox with teased tutorial)
![Image](https://github.com/xyflow/web/assets/9868315/74e34c97-9848-490a-aa8b-8e4432af6692)


Variant D1, D2, D3 (copy of new pro platform view)

![Image](https://github.com/xyflow/web/assets/9868315/73fa7d63-a32f-402b-ba94-d72faf9a262c)


![Image](https://github.com/xyflow/web/assets/9868315/95f9d6b2-7139-4343-a9b6-0e240bf4ece6)



![Image](https://github.com/xyflow/web/assets/9868315/14ebab0f-f4dd-4ef9-b228-23b8520631dd)

**Comment by chrtze** [comment]
wow, this is great! thanks @johnrobbjr.

**Comment by johnrobbjr** [comment]
talked through all options, decided to stick with current design, with changes:
-  @johnrobbjr be clearer in copy text about pro, maybe include benefits
- @chrtze make button send you to...
- - pro landing page if you don't have an account
- - log-in / platform if you do have an account / are logged in
