### ISSUE TITLE
OTelBin within showcase

### ISSUE THREAD

**Issue by bripkens** [xyflow/web#273]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

OTelBin

### Project Description

Web-based tool to facilitate OpenTelemetry collector configuration editing and verification

### Project Tags

OpenTelemetry, collector, observability, monitoring

### Link to the project website

https://otelbin.io/

### Link to project demo

https://github.com/dash0hq/otelbin

### Used Library

React Flow

### Upload a Project Screenshot

![screenshot](https://github.com/xyflow/web/assets/596443/301884e2-b5c2-42d9-910d-9a831ef94ec0)

### Additional Information

No additional info. Thank you for creating ReactFlow – we are happily supporting you through ReactFlow Pro! ❤️

**Comment by johnrobbjr** [comment]
LGTM, added: https://github.com/xyflow/web/tree/showcase/otelbin

Thanks for submitting! (and for your Pro subscription 💕)
