### ISSUE TITLE
JSON Sea (Submit Showcase)

### ISSUE THREAD

**Issue by altenull** [xyflow/web#277]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

JSON Sea

### Project Description

JSON data visualization tool that provides useful insights

### Project Tags

data visualization, open source, JSON

### Link to the project website

https://github.com/altenull/json-sea

### Link to project demo

https://www.jsonsea.com/

### Used Library

React Flow

### Upload a Project Screenshot

![JSON Sea Showcase](https://github.com/xyflow/web/assets/26947777/1f3bf71c-0872-4df4-b08e-6633ea7696a0)

### Additional Information

ReactFlow has allowed me to create my own open source project that can help other developers.
I've thanked you guys through the Discord channel before, but I'd like to appreciate the ReactFlow team again.

**Comment by johnrobbjr** [comment]
Looks great, added to showcase! https://github.com/xyflow/web/commit/4116c84faf06b2bf584a5a0d86faba3732bc65c8 

thanks for submitting ☺️
