### ISSUE TITLE
Food Former - A food creation game

### ISSUE THREAD

**Issue by JoshElgar** [xyflow/web#325]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Food Former

### Project Description

 A game where you mix foods together to make new ones. It's uses GPT3.5-turbo, React Flow, Vite, Tailwind and is hosted on Vercel.

### Project Tags

game, llm, food, entertainment

### Link to the project website

https://foodformer.com

### Link to project demo

https://foodformer.com

### Used Library

React Flow

### Upload a Project Screenshot

<img width="959" alt="foodformerscreenshot" src="https://github.com/xyflow/web/assets/7473757/bc2751c3-0023-4f44-a30f-bf3b00765f3f">

Video: https://twitter.com/joshelgar/status/1750141793377686000

**Comment by johnrobbjr** [comment]
Adding Food Former to the showcase in this pull request. Thanks for submitting!
https://github.com/xyflow/web/pull/331

**Comment by zebapy** [comment]
that site link is dead and somewhat NSFW result. Can this be reverted? @johnrobbjr

**Comment by johnrobbjr** [comment]
Removed from the showcase, thanks for the heads-up @zebapy 🙏🏻
