### ISSUE TITLE
AppBlocks No Code IoT Platform

### ISSUE THREAD

**Issue by salhk** [xyflow/web#329]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

AppBlocks

### Project Description

Drag and Drop Node Based Editor to Design Firmware for IoT Devices

### Project Tags

no-code,automation,development

### Link to the project website

https://appblocks.io

### Link to project demo

https://app.appblocks.io

### Used Library

React Flow

### Upload a Project Screenshot

![appblocks_editor_flow](https://github.com/xyflow/web/assets/14067560/449a1ec0-18d0-422d-981e-0b6c1ae9ba5d)

### Additional Information

![appblocks_editor_flow](https://github.com/xyflow/web/assets/14067560/4c12815a-32b9-493c-b4e8-bdf58bf6a76a)

**Comment by johnrobbjr** [comment]
Adding AppBlocks to the showcase in this pull request. Thanks for submitting!
https://github.com/xyflow/web/pull/331
