### ISSUE TITLE
Domino - Build Amazing Ideas, Piece by Piece

### ISSUE THREAD

**Issue by vinicvaz** [xyflow/web#330]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Domino 

### Project Description

Domino is an open source platform for creating and monitoring advanced workflows.

### Project Tags

no-code, ai, data, workflow, open-source

### Link to the project website

https://domino-workflows.io/

### Used Library

React Flow

### Upload a Project Screenshot

![image](https://github.com/xyflow/web/assets/50757601/39c30ac9-aef8-42f6-8b81-1e4ab0c742be)

### Additional Information

Domino, an open source web platform where:
- **End users** can easily build customized data workflows inside an intuitive visual interface, as simple as putting dominoes pieces together.
- **Developers** can easily create and re-use their code, seamlessly distributing it to a whole community of users.
- **Businesses** will foster a collaborative data-driven environment, where both dev and non-dev teams will actively contribute to the development of data and AI solutions.

**Comment by johnrobbjr** [comment]
Adding Domino to the showcase in this pull request. Thanks for submitting!
https://github.com/xyflow/web/pull/331
