### ISSUE TITLE
add flowise to the showcase

### ISSUE THREAD

**Issue by chrtze** [xyflow/web#332]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

flowise

### Project Description

Open source UI visual tool to build your customized LLM orchestration flow & AI agents

### Link to the project website

https://flowiseai.com/

### Used Library

React Flow

### Upload a Project Screenshot

![Screenshot 2024-02-06 at 12 54 13](https://github.com/xyflow/web/assets/3797215/923b0c9c-c2cc-4e62-bfc0-e0f719236de0)

**Comment by johnrobbjr** [comment]
This project is already in the showcase ✅
