### ISSUE TITLE
Showcase Request: SQL Forge

### ISSUE THREAD

**Issue by silvercrow08** [xyflow/web#335]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

SQL Forge

### Project Description

Node-based SQL query visualizer

### Project Tags

development, data visualization, database

### Open Source

- [ ] This project is Open Source

### Link to the project website

https://ronjones.pythonanywhere.com/

### Link to project demo

https://ronjones.pythonanywhere.com/

### Used Library

React Flow

### Upload a Project Screenshot

<img width="1269" alt="sql_forge" src="https://github.com/xyflow/web/assets/19838334/eeb0af45-d8c9-4df6-a662-ecdcdb557115">

### Anything else?

The project isn't open-source yet, but I plan to make the code available when I have some free time. Also working on an API using React Flow to visualize/document queries at scale!

**Comment by johnrobbjr** [comment]
Thank you for submitting to the project showcase, unfortunately we've decided not include your project in our Showcase. All the best
