### ISSUE TITLE
Aitino - Create AI Crews

### ISSUE THREAD

**Issue by antopiahk** [xyflow/web#349]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Aitino

### Project Description

Aitino is a platform that allows for the creation of teams of AI Agents to help you automate tasks and solve complex problems

### Project Tags

automation, task solving, multi-agent systems

### Open Source

- [ ] This project is Open Source

### Link to the project website

https://aiti.no

### Used Library

Svelte Flow

### Upload a Project Screenshot

![maeve_agents](https://github.com/xyflow/web/assets/31695089/a52b5fab-7cb4-4022-bccb-dbbd4b5f89dc)

**Comment by johnrobbjr** [comment]
Hey @antopiahk I tried to create an account using my email and it wasn't working so I wasn't able to try it out - if you fix this then we might be able to add it to the showcase. Cheers!
