### ISSUE TITLE
gradients differ from design

### ISSUE THREAD

**Issue by chrtze** [xyflow/web#357]
the gradients on the pro pages are too subtle and washed out. we should get closer to the design to make it look better.

live version:
![Screenshot 2024-03-26 at 11 43 38](https://github.com/xyflow/web/assets/3797215/fb9a77ac-fefe-4b4b-b6f8-e3145b171843)

expected:
![Screenshot 2024-03-26 at 11 43 21](https://github.com/xyflow/web/assets/3797215/20397199-bc52-4251-8b12-8ff2a26d193b)

**Comment by moklick** [comment]
I added a new background variant for the Hero component. For now we are only using it for the pro example page.
