### ISSUE TITLE
DataBlocks

### ISSUE THREAD

**Issue by rahul3v** [xyflow/web#374]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Datablock

### Project Description

Play around with data using datablocks

### Project Tags

no-code, datablock, automation, ai

### Open Source

- [X] This project is Open Source

### Link to the project website

https://github.com/rahul3v/datablock-demo

### Link to project demo

https://datablock-demo.vercel.app

### Used Library

React Flow

### Upload a Project Screenshot

![Screenshot 2024-04-24 at 07-08-23 Data Block App](https://github.com/xyflow/web/assets/24385409/f9d6d688-1ed5-4117-ab1b-d445b2410086)

### Anything else?

Currently in demo

**Comment by johnrobbjr** [comment]
Thanks for submitting your project, but unfortunately we've decided not to add this project to our showcase. All the best!

**Comment by rahul3v** [comment]
@johnrobbjr any feedback !!?
