### ISSUE TITLE
Shapes | Showcase

### ISSUE THREAD

**Issue by chapagainmanoj** [xyflow/web#390]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

dcode-store

### Project Description

Create simple Charts with different shapes and Save it for yourself.

### Project Tags

shapes, charts, flowcharts

### Open Source

- [X] This project is Open Source

### Link to the project website

https://dcode-store.github.io/shapes/

### Link to project demo

https://dcode-store.github.io/shapes/

### Used Library

React Flow

### Upload a Project Screenshot

<img width="1504" alt="Screenshot 2024-05-24 at 5 50 06 PM" src="https://github.com/xyflow/web/assets/4796993/325c4d63-15ae-45f0-86f9-9f8fc212f921">

**Comment by johnrobbjr** [comment]
Thanks for submitting, but unfortunately we've decided not to add this project to our the React Flow showcase - all the best!
