### ISSUE TITLE
The examples on the pages cannot be executed

### ISSUE THREAD

**Issue by Traveller23** [xyflow/web#391]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Which site are you suggesting a change for?

reactflow.dev

### What content is affected by this change?

The examples on the pages cannot be executed.
Even if I click on the link to jump to the site where the example is, I can only see the code and the execution still fails.

![1](https://github.com/xyflow/web/assets/117014547/0359f877-b9b2-4b7c-aa02-644d64629e61)
![2](https://github.com/xyflow/web/assets/117014547/16a6d1ce-6e98-44c7-bafa-6fdb783a6084)

### What part(s) of the article would you like to see updated?

online example

**Comment by hayleigh-dot-dev** [comment]
Hmm, I can't reproduce this on my machine. The error you're seeing there is coming from sandpack/codesandbox: if you check the network tab like it asks what does it say? Perhaps codesandbox were having some downtime issues when you looked or your internet was having some troubles.

**Comment by Traveller23** [comment]
> Hmm, I can't reproduce this on my machine. The error you're seeing there is coming from sandpack/codesandbox: if you check the network tab like it asks what does it say? Perhaps codesandbox were having some downtime issues when you looked or your internet was having some troubles.

Yes, the problem doesn't always exist. I can display the graph normally now.
