### ISSUE TITLE
Famtree | Showcase

### ISSUE THREAD

**Issue by kaustubhxd** [xyflow/web#393]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Famtree - Create your family tree instantly

### Project Description

Family Tree Builder

### Project Tags

family tree, entitree-flex, nextjs

### Open Source

- [ ] This project is Open Source

### Link to the project website

https://famtree.me/

### Link to project demo

https://www.famtree.me/try

### Used Library

React Flow

### Upload a Project Screenshot

<img width="1107" alt="Screenshot 2024-05-29 at 11 44 21 PM" src="https://github.com/xyflow/web/assets/56978887/3c5d17c3-ab01-4f07-9336-cf88afd639f3">

### Anything else?

Screenshot Tree Link - https://www.famtree.me/tree/002666f2-70a3-49cc-81cc-6cf894f78f5c

**Comment by kaustubhxd** [comment]
Hey guys, let me know if you could review this over this weekend?
cc: @johnrobbjr

**Comment by johnrobbjr** [comment]
Thanks for submitting, unfortunately we've decided not to include this project in the React Flow showcase. All the best!

**Comment by kaustubhxd** [comment]
Bummer! Thanks for considering! 😭
