### ISSUE TITLE
React Flow - Examples - Layout - Entitree Flex Tree layout example is not visible when user directly visits /examples

### ISSUE THREAD

**Issue by kaustubhxd** [xyflow/web#402]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Which site are you suggesting a change for?

reactflow.dev

### What content is affected by this change?

"Entitree Flex Tree" layout example is not visible when user visits https://reactflow.dev/examples
It's visible when one directly visits https://reactflow.dev/examples/layout/entitree-flex 

Can't replicate the bug on localhost so I don't really know how to fix it.
Works fine on the original PR preview: https://reactflow-website-git-fork-kaustubhxd-examples-en-2bd3de-xyflow.vercel.app/examples

⚠️ UPDATE: The example is now visible on /examples after a recent commit. But there's another bug, when you click on other examples like "Dagre Tree", the "Entitree Flex Tree" entry disappears again. Screencast: https://d.pr/v/1iee0c

### What part(s) of the article would you like to see updated?

Entitree Flex Tree should be visible when visiting /examples

### Additional information

Here's a screencast to help: 
Original screencast: https://d.pr/v/6QQpCh 
Entitree not visible when click on other examples: https://d.pr/v/1iee0c

**Comment by kaustubhxd** [comment]
⚠️ UPDATE: The example is now visible on /examples. But there's another bug, when you click on other examples like "Dagre Tree", the "Entitree Flex Tree" entry disappears again. Screencast: https://d.pr/v/1iee0c

**Comment by kaustubhxd** [comment]
@chrtze Open a PR for this: https://github.com/xyflow/web/pull/404

**Comment by chrtze** [comment]
hey @kaustubhxd, this should work now. it seemed to be a caching error while deploying.

**Comment by kaustubhxd** [comment]
@chrtze Should've guessed that's the issue..

https://github.com/xyflow/web/pull/404 
Is this PR still of any use?
