### ISSUE TITLE
Zen AI Svelteflow Showcase Request

### ISSUE THREAD

**Issue by lenzbelzner** [xyflow/web#403]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Zen AI

### Project Description

No code AI for workflow automation

### Project Tags

no-code, automation, ai

### Open Source

- [ ] This project is Open Source

### Link to the project website

https://getzenai.com/

### Used Library

Svelte Flow

### Upload a Project Screenshot

![Folie27](https://github.com/xyflow/web/assets/7090646/180250db-2259-4985-8bf8-9cca3e130600)

### Anything else?

We love Svelteflow - thank you! :D

**Comment by johnrobbjr** [comment]
Thanks for submitting! We'll add this to the showcase in pull request #463
