### ISSUE TITLE
Using Svelte Flow for creating workflows in Bridge - AI for explorers

### ISSUE THREAD

**Issue by jamesfebin** [xyflow/web#411]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Bridge

### Project Description

Local first AI for power users.

### Project Tags

llm workflows, ai workflows, prompt engineering.

### Open Source

- [ ] This project is Open Source

### Link to the project website

https://funwithsystems.com/bridge/

### Link to project demo

https://funwithsystems.com/bridge/

### Used Library

Svelte Flow

### Upload a Project Screenshot

<img width="1440" alt="Screenshot 2024-06-17 at 9 28 09 PM" src="https://github.com/xyflow/web/assets/3250220/cab62dfd-f082-4fed-b113-a5fbd24b9e11">

**Comment by johnrobbjr** [comment]
Thanks for submitting your project, but unfortunately we've decided not to add it to our showcase. All the best
