### ISSUE TITLE
Neural style transfer app using tensorflowjs and reactflow

### ISSUE THREAD

**Issue by muridot0** [xyflow/web#416]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

StylEase

### Project Description

Fast neural style transfer application ported to the browser with tensorflowjs

### Project Tags

styllization, neural style transfer, machine learning, tensorflowjs, image processing, open source

### Open Source

- [X] This project is Open Source

### Link to the project website

https://www.muri-o.com/stylease

### Link to project demo

https://www.muri-o.com/stylease

### Used Library

React Flow

### Upload a Project Screenshot

![image](https://github.com/xyflow/web/assets/76880145/1cbc5113-13fe-4c42-8f9d-fed6d307cff2)

**Comment by johnrobbjr** [comment]
Thank you for submitting your project, unfortunately we decided not to include it in our showcase. All the best
