### ISSUE TITLE
Add Graphologue to the showcase

### ISSUE THREAD

**Issue by peilingjiang** [xyflow/web#418]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Graphologue

### Project Description

Graphologue converts text-based responses from LLMs into graphical diagrams in real time.

### Project Tags

open source, LLM

### Open Source

- [X] This project is Open Source

### Link to the project website

https://github.com/ucsd-creativitylab/graphologue

### Link to project demo

https://graphologue.app

### Used Library

React Flow

### Upload a Project Screenshot

![graphologue-screenshot](https://github.com/xyflow/web/assets/25191575/67dfb520-47e8-4a15-9dd8-6ff01a78eb9c)

**Comment by johnrobbjr** [comment]
Thanks for submitting! We'll add this to the showcase in pull request #463
