### ISSUE TITLE
Add Agentok Studio to the Showcase

### ISSUE THREAD

**Issue by hughlv** [xyflow/web#424]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Agentok Studio

### Project Description

AutoGen Visualized - Visual Tools for Multi-Agent Development.

### Project Tags

workflow,LLM,open source,agentic app,multi-agent,autogen

### Open Source

- [X] This project is Open Source

### Link to the project website

https://github.com/hughlv/agentok

### Link to project demo

https://studio.agentok.ai/

### Used Library

React Flow

### Upload a Project Screenshot

<img width="2128" alt="screenshot-studio-1" src="https://github.com/xyflow/web/assets/817110/036d6452-3039-4b92-9d1a-07229a0e24ad">

**Comment by johnrobbjr** [comment]
Thanks for submitting! We'll add this to the showcase in pull request #463
