### ISSUE TITLE
Stack AI - Showcase

### ISSUE THREAD

**Issue by sanchezfdezjavier** [xyflow/web#427]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Stack AI 

### Project Description

Integrate AI into your organization. Stack AI boosts productivity by integrating AI with your data sources.

### Project Tags

AI 

### Open Source

- [ ] This project is Open Source

### Link to the project website

https://stack.ai

### Used Library

React Flow

### Upload a Project Screenshot

![Screenshot 2024-07-02 at 5 56 56 PM](https://github.com/xyflow/web/assets/32944505/0fa8c818-88c7-41f4-bc51-466778bd8430)

**Comment by moklick** [comment]
added!
