### ISSUE TITLE
Add Heuristica to the Showcase

### ISSUE THREAD

**Issue by hibernationTheory** [xyflow/web#437]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Heuristica

### Project Description

AI-powered mind maps and concept maps for visual learning, thinking and research.

### Project Tags

LLM, research

### Open Source

- [ ] This project is Open Source

### Link to the project website

https://www.heuristi.ca/

### Link to project demo

https://www.heuristi.ca/discover/48204e35-3a6e-4dcb-99ed-1fb91e45eb37

### Used Library

React Flow

### Upload a Project Screenshot

![heuristica-screenshot](https://github.com/user-attachments/assets/265dfda4-8ea2-4e1e-9f53-102428d3ccd9)

### Anything else?

Thanks for this awesome project. Heuristica wouldn't have been possible without you.

**Comment by moklick** [comment]
wow @hibernationTheory this looks so good 🔥🔥🔥 thanks for sharing!

**Comment by hibernationTheory** [comment]
> wow @hibernationTheory this looks so good 🔥🔥🔥 thanks for sharing!

Thanks so much @moklick glad you like it!

**Comment by moklick** [comment]
added!
