### ISSUE TITLE
Remove `getMarkerEnd` from documentation

### ISSUE THREAD

**Issue by bcakmakoglu** [xyflow/web#450]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Which site are you suggesting a change for?

reactflow.dev

### What content is affected by this change?

[`getMarkerEnd`](https://reactflow.dev/api-reference/utils/get-marker-end).

### What part(s) of the article would you like to see updated?

The docs are still listing `getMarkerEnd` under utils on the [api-reference page](https://reactflow.dev/api-reference).
This function doesn't exist anymore, so the page can be removed so users don't assume it's still available.
The migration guide mentions that `getMarkerEndId` was removed though I'm not sure if it references the same thing and the names are just mismatched.

**Comment by moklick** [comment]
thanks for your PR!
