### ISSUE TITLE
add a Chinese documentation of react-flow

### ISSUE THREAD

**Issue by MrXujiang** [xyflow/web#457]
### Please describe the feature that you want to propose

I wrote a Chinese documentation of react-flow. 

- github: https://github.com/MrXujiang/react-flow.
- website: http://react-flow.com

I greatly appreciate the author for open-sourcing such a great library.

**Comment by moklick** [comment]
After checking those links again, it feels like you just want to create another channel for your dooring app. If you want to help Chinese React Flow users to use our library, it would be helpful if you would link to the actual React Flow page. I can't find any link or words about the original library. I would appreciate if you would update your page and at least give some credits or anything.
