### ISSUE TITLE
Remove resize and rotate example because it is misleading

### ISSUE THREAD

**Issue by peterkogo** [xyflow/web#480]
The nodeResizer does not work with rotations and we will not support it.

We might want to encourage people to create their own simple resizers that work with rotation (maybe with handles changes their positions based on rotation as well) It's not that hard if you don't have to support everything possible with React Flow at the same time.

**Comment by chrtze** [comment]
- [ ] remove option to resize on the rotatable node
- [ ] remove option to rotate on the resizable node
- [ ] simply show labels "resizable" and "rotatable" on the nodes without the checkboxes
