### ISSUE TITLE
document `actInsideInputWithModifier ` useKeyPress option

### ISSUE THREAD

**Issue by Maquinours** [xyflow/web#481]
### Please describe the feature that you want to propose

Hi.

In my project, I use a UseKeyPress to trigger when CTRL + A is pressed to select all nodes & edges.
Also, my nodes contains inputs to enter some text.

The problem is, when I use CTRL + A on my input to select all the text inside, the UseKeyPress is triggered so it selects all my nodes.

Can we get a way to avoid useKeyPress to be triggered if a certain element is focused ? I tried the "nokey" className but it doesn't work in this case.

Thank you !

**Comment by chrtze** [comment]
Added this to the documentation: https://reactflow.dev/api-reference/hooks/use-key-press#options
