### ISSUE TITLE
Add ChartDB to the Showcase

### ISSUE THREAD

**Issue by johnnyfish** [xyflow/web#482]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

ChartDB

### Project Description

Open-source database diagrams editor, visualize and design your DB with a single query.

### Project Tags

LLM, data visualization, open source

### Open Source

- [X] This project is Open Source

### Link to the project website

https://chartdb.io

### Link to project demo

https://app.chartdb.io

### Used Library

React Flow

### Upload a Project Screenshot

![Snip20240824_3](https://github.com/user-attachments/assets/97bce1a1-d212-4688-a97d-e4798b6cfd9b)

### Anything else?

thank you!

**Comment by johnnyfish** [comment]
@moklick Any chance to give it a look pls 🙏🙂?

**Comment by moklick** [comment]
Cool project! Added :)
