### ISSUE TITLE
Floating edge example only supports a single edge.

### ISSUE THREAD

**Issue by netfl0** [xyflow/web#484]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: Svelte flow
- Browser and version: Firefox
- OS and version: Mac

### Describe the Bug

https://svelteflow.dev/examples/edges/simple-floating-edges

When you add a second edge, it does not "float" around like the first one.

### Steps to reproduce the bug or issue

1. Go to https://svelteflow.dev/examples/edges/simple-floating-edges
2. add two edges
3. move node around

### Expected behavior

I would expect:

Since most graphs will have multiple edges into a single node, it would make sense to demonstrate how to float all the edges.

**Comment by moklick** [comment]
It works for multiple edges but newly created edges need the correct type. You can achieve this by using `defaultEdgeOptions`:

```js
const defaultEdgeOptions = { type: 'floating' };
```

https://stackblitz.com/edit/eerzhw?file=src/example/App.svelte,src/example/nodes-and-edges.ts
