### ISSUE TITLE
ReactFlow v12: Typescript - use interface type with Node type

### ISSUE THREAD

**Issue by sponte** [xyflow/web#486]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version:   @xyflow/react": "^12.0.0-next.21"
- Browser and version: Safari Version 18.0 (20619.1.15.11.1)
- OS and version: MacOS 15.0 Beta (24A5264n)

### Describe the Bug

Trying to use interface type as a generic argument to the `Node` type, but it is not compatible with v12

Error message:

```
Type 'MyType' does not satisfy the constraint 'Record<string, unknown>'.
  Index signature for type 'string' is missing in type 'MyType'.ts(2344)
```

### Steps to reproduce the bug or issue

In your `reactflow` project, use v12 version and try the sample code below:

```typescript
interface MyType {
  name: string
  value?: any
}

type MyNodeType = Node<MyType, 'my-type'>
```

### Expected behavior

As a User
I would like to use interface types as generic parameters to the `Node` type
So that I get type safety and autocompletion in my project

### Screenshots or Videos

<img width="663" alt="image" src="https://github.com/xyflow/web/assets/47468/b728ed1a-a583-4fa1-bb6f-129a27e83e08">

**Comment by moklick** [comment]
We should make clear, that you need to use `type` instead of `interface` for the node data.

**Comment by moklick** [comment]
documented!

**Comment by buchananwill** [comment]
This is also currently causing me about two hours+ of compilation pain. Not sure why it has only just become an issue? I migrated to v12 a while back and didn't see it crop up then. My current "least effort" solution is this:

```
import { WorkSchemaNodeDto as WSNimport } from '@/api/zod-schemas/WorkSchemaNodeDtoSchema_';
import { Simplify } from 'type-fest';

type WorkSchemaNodeDto = Simplify<WSNimport>;
```

Can you give me any more insight as to why this problem is occurring?
