### ISSUE TITLE
use npm2yarn plugin 

### ISSUE THREAD

**Issue by moklick** [xyflow/web#530]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Which site are you suggesting a change for?

reactflow.dev

### What content is affected by this change?

There is great plugin for nextra that reduces boilerplate for all the places where we use multiple tabs for npm, pnpm, yarn and bun: https://nextra.site/docs/guide/advanced/npm2yarn 

This plugin can be used in all places where we do `npm install ...`. It's not possible to use it for `npm create ..`. 

### What part(s) of the article would you like to see updated?

all pages where we use Tabs for `npm install`, `yarn add` and so on

**Comment by chrtze** [comment]
We will consider this for our next development cycle where we will work on rehype plugins and nextra optimizations.
