### ISSUE TITLE
Unify Plays Showcase

### ISSUE THREAD

**Issue by solastley** [xyflow/web#537]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

Unify Plays

### Project Description

Build workflows to power GTM outbound sales strategies

### Project Tags

sales, outbound, GTM, workflow, automation

### Open Source

- [ ] This project is Open Source

### Link to the project website

https://www.unifygtm.com/plays

### Link to project demo

https://www.youtube.com/watch?v=2kwrcq15gaE&ab_channel=Unify

### Used Library

React Flow

### Upload a Project Screenshot

<img width="1728" alt="Screenshot 2024-11-20 at 4 39 56 PM" src="https://github.com/user-attachments/assets/1c748950-9145-485c-8f23-7cbce47ddd3b">

### Anything else?

Happy to demo this to the React Flow team if they're interested. Also, we are officially an xyflow sponsor!

**Comment by moklick** [comment]
Thanks, added! I would be interested in a demo :) Could you write a mail?
