### ISSUE TITLE
DatabaseSchemaNode: wrong attribute name

### ISSUE THREAD

**Issue by chrtze** [xyflow/web#616]
from email:

Bug on https://reactflow.dev/components/nodes/database-schema-node
The attribute name and type should be displayed in the preview, but the attribute name is shown twice . 
In DatabaseSchemaNode.tsx  update 
 <LabeledHandle

id={entry.title}   - >  {entry.type}
                  title={entry.title} -> {entry.type}

type="source"
                  position={Position.Right}
                  className="p-0"
                  handleClassName="p-0"
                  labelClassName="p-0"
                />

**Comment by neer-patel-11** [comment]
Please assign me this task, as I have noticed the bug.
